//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigesoft.Node.Sync.UI.ProxySync {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Sigesoft.Server.ServiceBus.ServiceLibrary" +
        "")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySync.ISync")]
    public interface ISync {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/GetData", ReplyAction="http://tempuri.org/ISync/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISync/GetDataUsingDataContractResponse")]
        Sigesoft.Node.Sync.UI.ProxySync.CompositeType GetDataUsingDataContract(Sigesoft.Node.Sync.UI.ProxySync.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/IsNodeAbleToSync", ReplyAction="http://tempuri.org/ISync/IsNodeAbleToSyncResponse")]
        bool IsNodeAbleToSync(ref Sigesoft.Common.OperationResult pobjOperationResult, int pintNodeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/SoftwareComponentCheck", ReplyAction="http://tempuri.org/ISync/SoftwareComponentCheckResponse")]
        System.Collections.Generic.List<Sigesoft.Server.WebClientAdmin.BE.softwarecomponentreleaseDto> SoftwareComponentCheck(ref Sigesoft.Common.OperationResult pobjOperationResult, ref System.Collections.Generic.List<Sigesoft.Common.SoftwareComponentCheckDto> pobjSoftwareComponentsToCheck);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/DownloadDeploymentFile", ReplyAction="http://tempuri.org/ISync/DownloadDeploymentFileResponse")]
        byte[] DownloadDeploymentFile(ref Sigesoft.Common.OperationResult pobjOperationResult, int pintDeploymentFileId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISync/AddDeploymentFile", ReplyAction="http://tempuri.org/ISync/AddDeploymentFileResponse")]
        bool AddDeploymentFile(int pintDeploymentFileId, byte[] filedata);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncChannel : Sigesoft.Node.Sync.UI.ProxySync.ISync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncClient : System.ServiceModel.ClientBase<Sigesoft.Node.Sync.UI.ProxySync.ISync>, Sigesoft.Node.Sync.UI.ProxySync.ISync {
        
        public SyncClient() {
        }
        
        public SyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public Sigesoft.Node.Sync.UI.ProxySync.CompositeType GetDataUsingDataContract(Sigesoft.Node.Sync.UI.ProxySync.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool IsNodeAbleToSync(ref Sigesoft.Common.OperationResult pobjOperationResult, int pintNodeId) {
            return base.Channel.IsNodeAbleToSync(ref pobjOperationResult, pintNodeId);
        }
        
        public System.Collections.Generic.List<Sigesoft.Server.WebClientAdmin.BE.softwarecomponentreleaseDto> SoftwareComponentCheck(ref Sigesoft.Common.OperationResult pobjOperationResult, ref System.Collections.Generic.List<Sigesoft.Common.SoftwareComponentCheckDto> pobjSoftwareComponentsToCheck) {
            return base.Channel.SoftwareComponentCheck(ref pobjOperationResult, ref pobjSoftwareComponentsToCheck);
        }
        
        public byte[] DownloadDeploymentFile(ref Sigesoft.Common.OperationResult pobjOperationResult, int pintDeploymentFileId) {
            return base.Channel.DownloadDeploymentFile(ref pobjOperationResult, pintDeploymentFileId);
        }
        
        public bool AddDeploymentFile(int pintDeploymentFileId, byte[] filedata) {
            return base.Channel.AddDeploymentFile(pintDeploymentFileId, filedata);
        }
    }
}
