//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/02 - 17:01:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="devolverproductosResult"/> and <see cref="devolverproductosResultDto"/>.
    /// </summary>
    public static partial class devolverproductosResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="devolverproductosResultDto"/> converted from <see cref="devolverproductosResult"/>.</param>
        static partial void OnDTO(this devolverproductosResult entity, devolverproductosResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="devolverproductosResult"/> converted from <see cref="devolverproductosResultDto"/>.</param>
        static partial void OnEntity(this devolverproductosResultDto dto, devolverproductosResult entity);

        /// <summary>
        /// Converts this instance of <see cref="devolverproductosResultDto"/> to an instance of <see cref="devolverproductosResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="devolverproductosResultDto"/> to convert.</param>
        public static devolverproductosResult ToEntity(this devolverproductosResultDto dto)
        {
            if (dto == null) return null;

            var entity = new devolverproductosResult();

            entity.IdProducto = dto.IdProducto;
            entity.Producto = dto.Producto;
            entity.Descripcion = dto.Descripcion;
            entity.Stock = dto.Stock;
            entity.Caracteristicas = dto.Caracteristicas;
            entity.CategoriaId = dto.CategoriaId;
            entity.Comision = dto.Comision;
            entity.CUOTA = dto.CUOTA;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="devolverproductosResult"/> to an instance of <see cref="devolverproductosResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="devolverproductosResult"/> to convert.</param>
        public static devolverproductosResultDto ToDTO(this devolverproductosResult entity)
        {
            if (entity == null) return null;

            var dto = new devolverproductosResultDto();

            dto.IdProducto = entity.IdProducto;
            dto.Producto = entity.Producto;
            dto.Descripcion = entity.Descripcion;
            dto.Stock = entity.Stock;
            dto.Caracteristicas = entity.Caracteristicas;
            dto.CategoriaId = entity.CategoriaId;
            dto.Comision = entity.Comision;
            dto.CUOTA = entity.CUOTA;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="devolverproductosResultDto"/> to an instance of <see cref="devolverproductosResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<devolverproductosResult> ToEntities(this IEnumerable<devolverproductosResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="devolverproductosResult"/> to an instance of <see cref="devolverproductosResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<devolverproductosResultDto> ToDTOs(this IEnumerable<devolverproductosResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
