//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/07/02 - 17:01:09
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="llenargrillasigesoftResult"/> and <see cref="llenargrillasigesoftResultDto"/>.
    /// </summary>
    public static partial class llenargrillasigesoftResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="llenargrillasigesoftResultDto"/> converted from <see cref="llenargrillasigesoftResult"/>.</param>
        static partial void OnDTO(this llenargrillasigesoftResult entity, llenargrillasigesoftResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="llenargrillasigesoftResult"/> converted from <see cref="llenargrillasigesoftResultDto"/>.</param>
        static partial void OnEntity(this llenargrillasigesoftResultDto dto, llenargrillasigesoftResult entity);

        /// <summary>
        /// Converts this instance of <see cref="llenargrillasigesoftResultDto"/> to an instance of <see cref="llenargrillasigesoftResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="llenargrillasigesoftResultDto"/> to convert.</param>
        public static llenargrillasigesoftResult ToEntity(this llenargrillasigesoftResultDto dto)
        {
            if (dto == null) return null;

            var entity = new llenargrillasigesoftResult();

            entity.EmpresaCliente = dto.EmpresaCliente;
            entity.Nombre_Componente = dto.Nombre_Componente;
            entity.IdComponente = dto.IdComponente;
            entity.IdServicio = dto.IdServicio;
            entity.Total = dto.Total;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="llenargrillasigesoftResult"/> to an instance of <see cref="llenargrillasigesoftResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="llenargrillasigesoftResult"/> to convert.</param>
        public static llenargrillasigesoftResultDto ToDTO(this llenargrillasigesoftResult entity)
        {
            if (entity == null) return null;

            var dto = new llenargrillasigesoftResultDto();

            dto.EmpresaCliente = entity.EmpresaCliente;
            dto.Nombre_Componente = entity.Nombre_Componente;
            dto.IdComponente = entity.IdComponente;
            dto.IdServicio = entity.IdServicio;
            dto.Total = entity.Total;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="llenargrillasigesoftResultDto"/> to an instance of <see cref="llenargrillasigesoftResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<llenargrillasigesoftResult> ToEntities(this IEnumerable<llenargrillasigesoftResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="llenargrillasigesoftResult"/> to an instance of <see cref="llenargrillasigesoftResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<llenargrillasigesoftResultDto> ToDTOs(this IEnumerable<llenargrillasigesoftResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
